### ISSUE TITLE
change microtis command to a shorter version

### ISSUE THREAD

**Issue by peterhencz** [fehersanyi/microtis-cli#3]
for example: mt or mc

**Comment by fehersanyi** [comment]
@peterhencz 

my plan would be to add a feature to select an alias for yourself, so you can configure for your own preference

something like: 
`microtis alias [meow]`
so you could run
`meow cica`

**Comment by peterhencz** [comment]
* reminder
Or mic

**Comment by fehersanyi-bitrise** [comment]
@peterhencz 

it depends on the argument, so the alias will be the first word you write after `microtis alias` :D

**Comment by fehersanyi** [comment]
implemented in 0.1
