### ISSUE TITLE
doesnt work with new branch

### ISSUE THREAD

**Issue by peterhencz** [fehersanyi/microtis-cli#6]
ha nincs upstreamelve egy uj branch, nem mukodik. marmint mukodik de pl bitbucketen nem latom a branchet

**Comment by fehersanyi** [comment]
ameg nem pusholsz elvileg nem jelenik meg online a branch sehol sem 🤔

**Comment by fehersanyi** [comment]
![screenshot 2019-03-08 at 15 58 09](https://user-images.githubusercontent.com/35537576/54036125-15af2380-41bb-11e9-8736-cf4241e3f8b2.png)
in fact it does 🤔
![screenshot 2019-03-08 at 15 58 59](https://user-images.githubusercontent.com/35537576/54036155-28c1f380-41bb-11e9-90d8-ec64e95ec811.png)
